export const TRIPS = 'TRIPS';
export const TRIPNAME = 'TRIPNAME';
export const TRIPDATESTART = 'TRIPDATESTART';
export const TRIPDATEEND = 'TRIPDATEEND';
export const ADD_TRIP = 'ADD_TRIP';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';